App:
    # path    
    path: /servers/develop/twitter-collage
    pathCache: /servers/cache/twitter-collage
    cacheFilePermissions: 777
    cacheDirPermissions: 777
    # url
    url: http://dev.twitter-collage.quodis.com
Store:
    # storage path
    path: /storage/develop/twitter-collage
    # storage public url
    url: http://store.dev.twitter-collage.quodis.com
    # created files and dirs in storage
    filePermissions: 600
    dirPermissions: 700
Twitter:
    urlSearch: "http://search.twitter.com/search.json"
    terms: "obama"
    rpp: 100
    pageLimit: 30
Collage:
    logoFile: assets/logo47x48.png
    defaultPic: assets/default48x48.png
    configFile: assets/config47x48.php
    cols: 47
    rows: 48
    tileSize: 11
Cache:
    enabled: 1
    TTL:
      collageConfig: 2000 
      tweetIds: 200
    servers:
        - host: localhost
          port: 11211
Db:
    schemaDir: schema
    databases:
        - name: twitter_collage
          schemaFile: db.sql
          defaults: &connectionDefaults
              host: localhost
              name: twitter_collage
              user: twitter_collage
              pass: twitter_collage
              client: localhost
          connections:
              read: 
                  <<: *connectionDefaults
                  mode: _modeRead
              write:
                  <<: *connectionDefaults
                  mode: _modeWrite
          installConnection:
              <<: *connectionDefaults
              name: 
              mode: _modeWrite
              user: install
              pass: install
UI:
    gaEnabled: "0"
    gaId: ""
    title: Twitter Collage
    keywords: ""
    description: ""
    templateDir: templates
    template : website
    stylesheet : "main.css?r=1"
    mainJs : "twitter-collage.js?r=1" 
