App:
    # path    
    path: /servers/prod/twitterparty
    pathLog: /var/log/twitterparty
    # url
    url: http://dev.twitterparty.quodis.com
Store:
    path: /servers/store/twitterparty
    filePermissions: 644
    dirPermissions: 755
    group: root
Twitter:
    urlSearch: "http://search.twitter.com/search.json"
    terms: "pleasedonttext"
    rpp: 100
    pageLimit: 30
    timeout:
        apiCall: 5
        imgFile: 1
Mosaic:
    logoFile: assets/logo48x47.png
    defaultPic: assets/default48x48.png
    configFile: assets/config48x47.php
    cols: 48
    rows: 47
    tileSize: 12
    colorDepth: 12
    internalComposite: 1
Jobs:
    twitter-search:
        period: 10
    image-process:
        period: 1
        dbLimit: 100
        imgLimit: 1000
    mosaic-build:
        period: 5
Cache:
    enabled: 1
    TTL:
        mosaicConfig: 2000 
        tweetIds: 200
    servers:
        - host: localhost
          port: 11211
Db:
    schemaDir: schema
    databases:
        - name: twitterparty
          schemaFile: db.sql
          defaults: &connectionDefaults
              host: localhost
              name: twitterparty
              user: twitterparty
              pass: twitterparty
              client: localhost
          connections:
              read: 
                  <<: *connectionDefaults
                  mode: _modeRead
              write:
                  <<: *connectionDefaults
                  mode: _modeWrite
          installConnection:
              <<: *connectionDefaults
              name: 
              mode: _modeWrite
              user: install
              pass: install
UI:
    gaEnabled: "0"
    gaId: ""
    title: "Firefox 4 Twitter Party"
    keywords: "Mozilla,Firefox, Firefox 4, Collage, Twitter,Tweet"
    description: "Firefox 4 Twitter Party is a visualization of Firefox 4 activity on Twitter. It is an experiment with exclusively open web tools and technologies."
    js: 
        general: "/assets/js/general.js?v=1"
        config: "/assets/js/config.js?v=1"
    css:
        main: "/assets/js/ftp.js?v=1"
        mosaic: "/assets/js/mosaic.js?v=1"
    pollLimit: 100