App:
    # path    
    path: /servers/sites/quodis/twitter-collage
    pathLog: /var/log/twitter-collage
    pathCache: /servers/cache/twitter-collage
    cacheFilePermissions: 664
    cacheDirPermissions: 775
    cacheGroup: www-data
    # url
    url: http://twitter-collage.quodis.worker
Store:
    # storage path
    path: /servers/store/twitter-collage
    # storage public url
    url: http://store.twitter-collage.quodis.worker
    # created files and dirs in storage
    filePermissions: 664
    dirPermissions: 775
Twitter:
    urlSearch: "http://search.twitter.com/search.json"
    terms: "pleasedonttext"
    rpp: 100
    pageLimit: 1
    timeout:
        apiCall: 5
        imgFile: 1
Collage:
    logoFile: assets/logo48x47.png
    defaultPic: assets/default48x48.png
    configFile: assets/config48x47.php
    cols: 48
    rows: 47
    tileSize: 12
    colorDepth: 12
    internalComposite: 1
Jobs:
    twitter-search:
        period: 10
    make-images:
        period: 1
        dbLimit: 100
        imgLimit: 1000
    collage-build:
        period: 5
Cache:
    enabled: 1
    TTL:
        collageConfig: 2000 
        tweetIds: 200
    servers:
        - host: localhost
          port: 11211
Db:
    schemaDir: schema
    databases:
        - name: twitter_collage
          schemaFile: db.sql
          defaults: &connectionDefaults
              host: localhost
              name: twitter_collage
              user: twitter_collage
              pass: twitter_collage
              client: localhost
          connections:
              read: 
                  <<: *connectionDefaults
                  mode: _modeRead
              write:
                  <<: *connectionDefaults
                  mode: _modeWrite
          installConnection:
              <<: *connectionDefaults
              name: 
              mode: _modeWrite
              user: install
              pass: install
UI:
    gaEnabled: "0"
    gaId: ""
    title: Twitter Collage
    keywords: ""
    description: ""
    templateDir: templates
    template : website
    stylesheet : "main.css?r=1"
    mainJs : "twitter-collage.js?r=1"
    pollLimit: 100 
